version: '3.7'
services:
  link_shorter_app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 5000
    volumes:
      - .:/app
    env_file:
      - ./app/.env
    ports:
      - 5000:5000
    depends_on:
      - link_shorter_db

  link_shorter_db:
    container_name: link_shorter_db
    restart: always
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234

volumes:
    postgres_data: